# Generated by Django 6.0.4 on 2026-04-28 16:03

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.UUIDField(default=profiles.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst')], default='analyst', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['github_id'], name='profiles_pl_github__3d5dbb_idx'), models.Index(fields=['username'], name='profiles_pl_usernam_fb2b72_idx'), models.Index(fields=['role'], name='profiles_pl_role_c9af2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=profiles.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='profiles.platformuser')),
            ],
            options={
                'indexes': [models.Index(fields=['token_hash'], name='profiles_re_token_h_a6117d_idx'), models.Index(fields=['expires_at'], name='profiles_re_expires_c3729c_idx'), models.Index(fields=['revoked_at'], name='profiles_re_revoked_79252b_idx')],
            },
        ),
    ]
